source: /
paths:
  data: data
  collections: content
  includes: layouts
  layouts: layouts
  static: static
  uploads: static/uploads
  source: ''
  archetypes: archetypes
  assets: assets
  content: content
  pages: content
  publish: public
  config: ''
editor:
  default_path:
source_editor:
  tab_size: 2
  theme: monokai
  show_gutter: true
timezone: Etc/UTC
collections_config_override: false
