source: site
paths:
  data: data
  collections: content
  includes: layouts
  layouts: layouts
  static: static
  uploads: static/uploads
  source: site
  archetypes: archetypes
  assets: assets
  content: content
  pages: content
  publish: public
  config: ''
collections_config:
  pages:
    path: content
    url: '/[relative_base_path]'
    output: true
    filter: strict
    parse_branch_index: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  blog:
    path: content/blog
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  data:
    path: data
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
data_config: {}
timezone: Etc/UTC
plugins:
  - jekyll-seo-tag

